export const sampleMCPs = [
  {
    id: "weather-mcp-001",
    name: "weather.forecast",
    description: "Real-time weather data and forecasting with global coverage and severe weather alerts",
    tags: ["weather", "api", "forecast", "alerts", "air-quality"],
    domain: "weather",
    validated: true,
    popularity: 95,
    source_url: "https://github.com/example/weather-mcp",
    source_platform: "github",
    confidence_score: 0.95,
    file_type: "json",
    repository: "example/weather-mcp",
    stars: 245,
    created_at: "2024-01-15T10:30:00Z"
  },
  {
    id: "search-mcp-002", 
    name: "web.search",
    description: "Comprehensive web search and content retrieval with multiple search engines",
    tags: ["search", "web", "content", "news", "images"],
    domain: "search",
    validated: true,
    popularity: 88,
    source_url: "https://github.com/example/web-search-mcp",
    source_platform: "github",
    confidence_score: 0.92,
    file_type: "json",
    repository: "example/web-search-mcp",
    stars: 189,
    created_at: "2024-01-14T14:20:00Z"
  },
  {
    id: "calc-mcp-003",
    name: "math.calculator", 
    description: "Advanced mathematical calculations, formula evaluation, and scientific computing",
    tags: ["math", "calculator", "equations", "statistics", "linear-algebra"],
    domain: "math",
    validated: true,
    popularity: 76,
    source_url: "https://github.com/example/math-calculator-mcp",
    source_platform: "github",
    confidence_score: 0.89,
    file_type: "json",
    repository: "example/math-calculator-mcp",
    stars: 156,
    created_at: "2024-01-13T09:15:00Z"
  },
  {
    id: "ecommerce-mcp-004",
    name: "ecommerce.store",
    description: "Complete e-commerce platform with inventory management, payments, and analytics",
    tags: ["ecommerce", "shopping", "payments", "inventory", "analytics"],
    domain: "ecommerce",
    validated: true,
    popularity: 82,
    source_url: "https://github.com/example/ecommerce-mcp",
    source_platform: "github",
    confidence_score: 0.87,
    file_type: "json",
    repository: "example/ecommerce-mcp",
    stars: 203,
    created_at: "2024-01-12T16:45:00Z"
  },
  {
    id: "calendar-mcp-005",
    name: "calendar.events",
    description: "Advanced calendar management with multiple provider integrations and smart scheduling",
    tags: ["calendar", "events", "scheduling", "sync", "analytics"],
    domain: "productivity",
    validated: true,
    popularity: 71,
    source_url: "https://github.com/example/calendar-mcp",
    source_platform: "github",
    confidence_score: 0.84,
    file_type: "json",
    repository: "example/calendar-mcp",
    stars: 134,
    created_at: "2024-01-11T11:20:00Z"
  },
  {
    id: "social-mcp-006",
    name: "social.media",
    description: "Multi-platform social media management with content creation and analytics",
    tags: ["social", "media", "analytics", "content", "monitoring"],
    domain: "social",
    validated: true,
    popularity: 64,
    source_url: "https://github.com/example/social-media-mcp",
    source_platform: "github",
    confidence_score: 0.78,
    file_type: "json",
    repository: "example/social-media-mcp",
    stars: 98,
    created_at: "2024-01-10T08:30:00Z"
  },
  {
    id: "ai-mcp-007",
    name: "ai.assistant",
    description: "Advanced AI assistant with multiple model integrations and specialized capabilities",
    tags: ["ai", "assistant", "nlp", "computer-vision", "translation"],
    domain: "ai",
    validated: true,
    popularity: 93,
    source_url: "https://huggingface.co/example/ai-assistant-mcp",
    source_platform: "huggingface",
    confidence_score: 0.96,
    file_type: "yaml",
    repository: "example/ai-assistant-mcp",
    stars: 312,
    created_at: "2024-01-09T15:45:00Z"
  },
  {
    id: "dev-mcp-008",
    name: "development.tools",
    description: "Comprehensive development tools for code analysis, deployment, and project management",
    tags: ["development", "code-analysis", "deployment", "documentation", "ci-cd"],
    domain: "development",
    validated: true,
    popularity: 79,
    source_url: "https://github.com/example/dev-tools-mcp",
    source_platform: "github",
    confidence_score: 0.91,
    file_type: "json",
    repository: "example/dev-tools-mcp",
    stars: 267,
    created_at: "2024-01-08T12:15:00Z"
  }
];